name: place_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.3.0+1
  provider: ^6.0.2
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0 <3.0.0"

flutter:
  assets:
    - assets/

  uses-material-design: true
